/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hectordavid1228' at '17/02/16 04:43 PM' with Gradle 2.6
 *
 * @author hectordavid1228, @date 17/02/16 04:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
