/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'monitor' at '17/02/16 05:05 PM' with Gradle 2.6
 *
 * @author monitor, @date 17/02/16 05:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
